# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
group: stable
cache: packages
warnings_are_errors: true

os:
   - linux
   - osx
r:
   - release
   - devel
